[profile.default]
solc-version = "0.8.24"
libs = ['lib']
optimizer = true
optimizer_runs = 420_000
fuzz_max_global_rejects = 420_000
evm_version = 'cancun'

gas_reports = [
    "CounterHook",
]

remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/contracts",
    "@uniV4/=lib/v4-core"
]